import { IngredientValue } from "./value-objects/IngredientValue.js";
import TagValue from "./value-objects/TagValue.js";

export const meatTypes: IngredientValue[] = [
  new IngredientValue("pork", 2.4, "GiPig"),
  new IngredientValue("chicken", 1.9, "GiChicken"),
  new IngredientValue("shrimp", 1.1, "GiShrimp"),
  new IngredientValue("beef", 2.5, "GiSteak"),
  new IngredientValue("turkey", 1.35, "GiRoastChicken"),
  new IngredientValue("duck", 3.37, "GiDuck"),
  new IngredientValue("lamb", 2.94, "GiSheep"),
  new IngredientValue("salmon", 2.08, "GiSalmon"),
  new IngredientValue("tuna", 1.44, "GiFishBucket"),
  new IngredientValue("cod", 1.05, "GiFriedFish"),
  new IngredientValue("tilapia", 1.29, "GiTropicalFish"),
  new IngredientValue("bacon", 5.41, "GiBacon"),
  new IngredientValue("ham", 1.45, "GiMeatHook"),
  new IngredientValue("sausage", 3.01, "GiSausage"),
  new IngredientValue("tofu", 0.76, "GiCube"),
  new IngredientValue("tempeh", 1.93, "GiGrainBundle"),
  new IngredientValue("seitan", 1.2, "GiWheat"),
  new IngredientValue("eggs", 1.55, "GiFriedEggs"),
  new IngredientValue("chickpeas", 1.64, "GiBeanstalk"),
  new IngredientValue("black beans", 1.32, "GiAcorn"),
  new IngredientValue("lentils", 1.16, "GiGrain"),
  new IngredientValue("crab", 0.97, "GiCrab"),
  new IngredientValue("lobster", 0.89, "GiCrabClaw"),
  new IngredientValue("scallops", 1.11, "GiScallop"),
  new IngredientValue("mussels", 1.72, "GiMussel"),
  new IngredientValue("venison", 1.58, "GiDeerHead"),
  new IngredientValue("bison", 1.43, "GiBison"),
  new IngredientValue("quail", 2.34, "GiChickenLeg"),
  new IngredientValue("goat", 1.09, "GiGoat"),
  new IngredientValue("veal", 1.72, "GiCow"),
  new IngredientValue("chorizo", 4.55, "GiSlicedSausage"),
  new IngredientValue("prosciutto", 1.95, "GiMeatCleaver"),
  new IngredientValue("pepperoni", 5.04, "GiSausagesRibbon"),
  new IngredientValue("rabbit", 1.73, "GiRabbit"),
  new IngredientValue("octopus", 0.82, "GiOctopus"),
  new IngredientValue("anchovies", 2.1, "GiSchoolOfFish"),
  new IngredientValue("sardines", 2.08, "GiCannedFish"),
  new IngredientValue("mackerel", 2.05, "GiFishSmoking"),
  new IngredientValue("halibut", 1.11, "GiFlatfish"),
  new IngredientValue("catfish", 1.05, "GiFishScales"),
  new IngredientValue("ground turkey", 1.43, "GiManualMeatGrinder"),
  new IngredientValue("meatballs", 2.32, "GiMeat"),
  new IngredientValue("falafel", 3.33, "GiDumpling"),
  new IngredientValue("paneer", 2.65, "GiCheeseWedge"),
  new IngredientValue("jackfruit", 0.95, "GiPineapple"),
];

export const sideTypes: IngredientValue[] = [
  new IngredientValue("salad", 0.2, "GiHerbsBundle"),
  new IngredientValue("potatoes", 0.9, "GiPotato"),
  new IngredientValue("rice", 1.3, "GiBowlOfRice"),
  new IngredientValue("pasta", 1.6, "GiNoodles"),
  new IngredientValue("quinoa", 1.2, "GiGrain"),
  new IngredientValue("couscous", 1.12, "GiGrainBundle"),
  new IngredientValue("mashed potatoes", 0.88, "GiPotato"),
  new IngredientValue("sweet potatoes", 0.86, "GiPotato"),
  new IngredientValue("fries", 3.12, "GiFrenchFries"),
  new IngredientValue("bread", 2.65, "GiBread"),
  new IngredientValue("naan", 2.62, "GiButterToast"),
  new IngredientValue("tortilla", 2.18, "GiBreadSlice"),
  new IngredientValue("noodles", 1.38, "GiFastNoodles"),
  new IngredientValue("polenta", 0.7, "GiTripleCorn"),
  new IngredientValue("risotto", 1.3, "GiRiceCooker"),
  new IngredientValue("roasted vegetables", 0.65, "GiCarrot"),
  new IngredientValue("steamed broccoli", 0.34, "GiBroccoli"),
  new IngredientValue("coleslaw", 1.5, "GiCurledLeaf"),
  new IngredientValue("mac and cheese", 1.64, "GiCheeseWedge"),
  new IngredientValue("hummus", 1.66, "GiBeanstalk"),
  new IngredientValue("baked beans", 1.27, "GiAcorn"),
  new IngredientValue("corn", 0.86, "GiCorn"),
  new IngredientValue("grits", 0.6, "GiPopcorn"),
  new IngredientValue("flatbread", 2.74, "GiSlicedBread"),
  new IngredientValue("pita bread", 2.75, "GiPretzel"),
  new IngredientValue("greek salad", 0.7, "GiVineLeaf"),
  new IngredientValue("pilaf", 1.5, "GiBowlOfRice"),
  new IngredientValue("fried rice", 1.63, "GiRiceCooker"),
  new IngredientValue("dumplings", 2.2, "GiDumplingBao"),
  new IngredientValue("spring rolls", 1.5, "GiLeafSwirl"),
  new IngredientValue("garlic bread", 3.5, "GiGarlic"),
  new IngredientValue("onion rings", 4.11, "GiBellPepper"),
  new IngredientValue("brown rice", 1.11, "GiBowlOfRice"),
  new IngredientValue("wild rice", 1.01, "GiRiceCooker"),
  new IngredientValue("tabbouleh", 0.9, "GiChestnutLeaf"),
  new IngredientValue("ratatouille", 0.5, "GiTomato"),
  new IngredientValue("gnocchi", 1.31, "GiPotato"),
];

export const cuisineStyles: TagValue[] = [
  new TagValue("asian"),
  new TagValue("indian"),
  new TagValue("italian"),
  new TagValue("mexican"),
  new TagValue("thai"),
  new TagValue("chinese"),
  new TagValue("japanese"),
  new TagValue("korean"),
  new TagValue("vietnamese"),
  new TagValue("mediterranean"),
  new TagValue("greek"),
  new TagValue("french"),
  new TagValue("spanish"),
  new TagValue("american"),
  new TagValue("cajun"),
  new TagValue("middle-eastern"),
  new TagValue("moroccan"),
  new TagValue("ethiopian"),
  new TagValue("caribbean"),
  new TagValue("german"),
  new TagValue("british"),
  new TagValue("southern"),
  new TagValue("tex-mex"),
  new TagValue("fusion"),
  new TagValue("peruvian"),
  new TagValue("brazilian"),
  new TagValue("lebanese"),
  new TagValue("turkish"),
  new TagValue("filipino"),
  new TagValue("indonesian"),
  new TagValue("portuguese"),
  new TagValue("hawaiian"),
];

export const flavorProfiles: TagValue[] = [
  new TagValue("creamy"),
  new TagValue("tangy"),
  new TagValue("tomato-y"),
  new TagValue("spicy"),
  new TagValue("smoky"),
  new TagValue("sweet"),
  new TagValue("savory"),
  new TagValue("umami"),
  new TagValue("herby"),
  new TagValue("garlicky"),
  new TagValue("citrusy"),
  new TagValue("nutty"),
  new TagValue("buttery"),
  new TagValue("peppery"),
  new TagValue("sour"),
  new TagValue("bitter"),
  new TagValue("earthy"),
  new TagValue("fresh"),
  new TagValue("zesty"),
  new TagValue("rich"),
  new TagValue("mild"),
  new TagValue("bold"),
  new TagValue("aromatic"),
  new TagValue("caramelized"),
  new TagValue("tart"),
  new TagValue("salty"),
  new TagValue("crispy"),
  new TagValue("char-grilled"),
  new TagValue("fermented"),
  new TagValue("honeyed"),
];
